name: 🚀 Submit New Project
description: Submit a new open source project to be added to the directory
title: "[NEW PROJECT] "
labels: ["submission"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for submitting a project! We'll automatically validate and review your submission.

  - type: input
    id: url
    attributes:
      label: Repository URL
      description: GitHub repository URL
      placeholder: "https://github.com/username/project"
    validations:
      required: true

  - type: textarea
    id: tags
    attributes:
      label: Additional Tags (Optional)
      description: |
        Add any additional tags, one per line.

        **Best Practice:** We recommend adding topics/tags directly to your GitHub repository instead. 
        Go to your repo → Settings → Topics and add relevant tags there. This helps with discoverability across GitHub! These will be automatically pulled in.
      placeholder: |
        architecture
        construction
        engineering

  - type: dropdown
    id: platforms
    attributes:
      label: Supported Platforms
      description: Which platforms does your project support? Select all that apply.
      multiple: true
      options:
        - windows
        - linux
        - macos
        - web
        - mobile
        - desktop
        - cloud
        - ios
        - android

  # - type: dropdown
  #   id: frameworks
  #   attributes:
  #     label: Frameworks/Technologies Used
  #     description: What frameworks or key technologies does your project use? Select all that apply.
  #     multiple: true
  #     options:
  #       - react
  #       - vue
  #       - angular
  #       - svelte
  #       - threejs
  #       - babylonjs
  #       - unity
  #       - unreal
  #       - electron
  #       - flutter
  #       - dotnet
  #       - nodejs
  #       - django
  #       - flask
  #       - spring
  #       - qt
  #       - wpf
  #       - winui
  #       - xamarin
  - type: checkboxes
    id: project_requirements
    attributes:
      label: Project Requirements
      description: Please confirm your project meets these requirements
      options:
        - label: The project is hosted on GitHub
          required: true
        - label: It has a clear open-source license (check your repo for a LICENSE file)
          required: true
        - label: It is directly connected to the AEC (Architecture, Engineering, Construction) industry
          required: true
        - label: The repository has a README file with project description
          required: true
